import os

os.environ["HAYSTACK_PROGRESS_BARS"]='0'
OPENSEARCH_HOST = os.getenv('OPENSEARCH_HOST')
OPENSEARCH_PORT = os.getenv('OPENSEARCH_PORT')
OPENSEARCH_USERNAME = os.getenv('OPENSEARCH_USERNAME')
OPENSEARCH_PASSWORD = os.getenv('OPENSEARCH_PASSWORD')
SAGEMAKER_MODEL_ENDPOINT = os.getenv('SAGEMAKER_MODEL_ENDPOINT')
AWS_PROFILE_NAME = os.getenv('AWS_PROFILE_NAME')
AWS_REGION_NAME = os.getenv('AWS_REGION_NAME')